### ISSUE TITLE
only works for transitions via javascript

### ISSUE THREAD

**Issue by ianstormtaylor** [anthonyshort/after-transition#1]
doesn't work if you're using css to apply the transitions, and only toggling classnames in javascript.

from https://github.com/anthonyshort/has-transitions/pull/1

**Comment by ianstormtaylor** [comment]
no current way to solve this: http://stackoverflow.com/questions/14348856/detect-if-element-is-being-transitioned

lame from spec standpoint

**Comment by yields** [comment]
ugh, just ugh.

maybe use `.getComputedStyle()['transition']` and call it a day ?

**Comment by ianstormtaylor** [comment]
https://github.com/anthonyshort/after-transition/issues/2 totally agree ;p
